# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
  documentation:
    info:
      title: Instagum
      description: réseau social
      version: 1.0.0
    security:
      - jwt: []
    components:
      securitySchemes:
        jwt:
          type: apiKey
          in: header
          name: Authorization
  areas:
      path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
          - ^/api(?!/doc$)
        