nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://127.0.0.1:8000']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: true
        forced_allow_origin_value: null
